import React, { useEffect, useState } from 'react';
import {
  BarChart3,
  TrendingUp,
  AlertCircle,
  Building2,
  GraduationCap,
  Sparkles,
  ShieldCheck,
  Award,
} from 'lucide-react';
import { reportsApi } from '../services/api';

export const Reports: React.FC = () => {
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadReport();
  }, []);

  const loadReport = async () => {
    setLoading(true);
    try {
      const res = await reportsApi.getInstitutionalReport();
      setReport(res);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  if (loading || !report) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] py-20">
        <div className="w-8 h-8 border-3 border-blue-600 border-t-transparent rounded-full animate-spin mb-3" />
        <div className="text-xs font-semibold text-slate-500">Compiling institutional aggregate leadership report...</div>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      {/* Header */}
      <div>
        <div className="flex items-center gap-2 text-blue-600 font-bold text-xs tracking-wider uppercase">
          <BarChart3 className="w-4 h-4" />
          <span>Academic Leadership Intelligence</span>
        </div>
        <h1 className="text-2xl md:text-3xl font-bold text-slate-900 mt-1 tracking-tight">
          Institutional Early-Warning Patterns
        </h1>
        <p className="text-sm text-slate-500 mt-1 max-w-3xl leading-relaxed">
          Executive aggregate statistics for Deans, HoDs, and Principals. Identifies systemic curricular bottlenecks while preserving individual student privacy.
        </p>
      </div>

      {/* Strategic Insights Banner */}
      <div className="bg-gradient-to-br from-slate-950 via-slate-900 to-indigo-950 text-white rounded-2xl p-6 md:p-8 shadow-xl border border-indigo-900/40 space-y-4">
        <div className="flex items-center gap-2.5 font-bold text-base text-amber-400">
          <Sparkles className="w-5 h-5 animate-pulse text-amber-400" />
          <span>Key Systemic Findings & Bottleneck Observations</span>
        </div>
        <ul className="space-y-2 text-xs md:text-sm text-slate-300 pl-4 list-disc leading-relaxed">
          {report.insights.map((insight: string, idx: number) => (
            <li key={idx} className="leading-relaxed">
              {insight}
            </li>
          ))}
        </ul>
      </div>

      {/* Course Concentration Analysis */}
      <div className="bg-white p-6 md:p-8 rounded-2xl border border-slate-200/90 shadow-2xs space-y-6">
        <div>
          <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
            <GraduationCap className="w-5 h-5 text-blue-600" />
            <span>Curricular Risk Concentration by Course</span>
          </h2>
          <p className="text-xs text-slate-500 mt-1">
            Measures the percentage share of academic difficulty warnings generated by each course curriculum.
          </p>
        </div>

        <div className="overflow-x-auto rounded-xl border border-slate-200/80">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="bg-slate-50/90 border-b border-slate-200 text-slate-600 font-bold uppercase tracking-wider text-[11px]">
                <th className="py-3.5 px-6 border-r border-slate-100">Course / Program</th>
                <th className="py-3.5 px-6 border-r border-slate-100">Code</th>
                <th className="py-3.5 px-6 text-center border-r border-slate-100">Total Warnings</th>
                <th className="py-3.5 px-6 text-center border-r border-slate-100">Academic Warnings</th>
                <th className="py-3.5 px-6 text-right border-r border-slate-100">Academic Share %</th>
                <th className="py-3.5 px-6">Concentration Indicator</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 font-medium">
              {report.by_course.map((c: any) => (
                <tr key={c.course_id} className="hover:bg-blue-50/30 transition-colors">
                  <td className="py-4 px-6 font-bold text-slate-900 border-r border-slate-100">{c.name}</td>
                  <td className="py-4 px-6 text-slate-500 font-mono text-xs border-r border-slate-100">{c.code}</td>
                  <td className="py-4 px-6 text-center font-bold text-slate-800 border-r border-slate-100">{c.total_alerts}</td>
                  <td className="py-4 px-6 text-center font-bold text-blue-600 border-r border-slate-100">{c.academic_alerts}</td>
                  <td className="py-4 px-6 text-right font-black text-slate-900 border-r border-slate-100">{c.academic_concentration_pct}%</td>
                  <td className="py-4 px-6">
                    <div className="w-full bg-slate-100 rounded-full h-2.5 max-w-[140px] overflow-hidden">
                      <div
                        className={`h-full rounded-full transition-all duration-700 ease-out ${
                          c.academic_concentration_pct >= 25
                            ? 'bg-rose-500'
                            : c.academic_concentration_pct >= 15
                            ? 'bg-amber-500'
                            : 'bg-blue-600'
                        }`}
                        style={{ width: `${Math.min(100, c.academic_concentration_pct * 2.5)}%` }}
                      />
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Department Aggregate Summary */}
      <div className="bg-white p-6 md:p-8 rounded-2xl border border-slate-200/90 shadow-2xs space-y-6">
        <div>
          <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
            <Building2 className="w-5 h-5 text-blue-600" />
            <span>Faculty & Department Comparative Metrics</span>
          </h2>
          <p className="text-xs text-slate-500 mt-1">Enrolment vs alert rates and resolution rates across academic schools</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {report.by_department.map((d: any) => (
            <div
              key={d.department_id}
              className="bg-slate-50/80 p-5 rounded-2xl border border-slate-200/80 space-y-4 interactive-card hover:-translate-y-1 hover:shadow-md hover:border-blue-300 transition-all duration-200"
            >
              <div className="flex items-center justify-between">
                <span className="font-bold text-sm text-slate-900">{d.name}</span>
                <span className="px-2.5 py-0.5 rounded-md text-[11px] font-mono font-bold bg-white border border-slate-200 text-blue-700">
                  {d.code}
                </span>
              </div>

              <div className="space-y-2 text-xs text-slate-600">
                <div className="flex justify-between">
                  <span>Enrolled Cohort:</span>
                  <span className="font-semibold text-slate-800">{d.student_count} students</span>
                </div>
                <div className="flex justify-between">
                  <span>Total Early Warnings:</span>
                  <span className="font-bold text-blue-600">{d.total_alerts} alerts</span>
                </div>
                <div className="flex justify-between">
                  <span>High Severity Share:</span>
                  <span className="font-bold text-rose-600">{d.high_severity_alerts}</span>
                </div>
                <div className="flex justify-between border-t border-slate-200 pt-2">
                  <span className="font-medium text-slate-700">Alert Incidence Rate:</span>
                  <span className="font-bold text-slate-900">{d.alert_rate_pct}%</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
